version: '3.8'

services:
  app:
    build: .
    image: desafio-rubix-python
    container_name: rubix_app
    stdin_open: true 
    tty: true
    volumes:
      - ./src/data:/app/src/data
      - ./logs:/app/logs